' LLM MultiChat - Starter
' Creates temporary PowerShell script for updates
' Detects system language and uses appropriate translations

Option Explicit

Dim WshShell, FSO, AppPath, TempPath, PsScript, Result
Set WshShell = CreateObject("WScript.Shell")
Set FSO = CreateObject("Scripting.FileSystemObject")

AppPath = FSO.GetParentFolderName(WScript.ScriptFullName)
TempPath = WshShell.ExpandEnvironmentStrings("%TEMP%")
PsScript = TempPath & "\llm-multichat-setup.ps1"

' PowerShell-Script erstellen
CreateSetupScript

' PowerShell ausfuehren
Result = WshShell.Run("powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & PsScript & """ -AppPath """ & AppPath & """", 0, True)

' Temporaeres Script loeschen
On Error Resume Next
FSO.DeleteFile PsScript
On Error GoTo 0

' Wenn Setup erfolgreich, App starten
If FSO.FileExists(AppPath & "\software\src\main\main.js") Then
    WshShell.CurrentDirectory = AppPath & "\software\app"
    WshShell.Run "cmd /c npm start", 0, False
End If

' ============================================

Sub CreateSetupScript()
    Dim File
    Set File = FSO.CreateTextFile(PsScript, True)
    
    File.WriteLine "param([string]$AppPath)"
    File.WriteLine ""
    File.WriteLine "$ErrorActionPreference = 'SilentlyContinue'"
    File.WriteLine "$ProgressPreference = 'SilentlyContinue'"
    File.WriteLine ""
    File.WriteLine "# Detect system language"
    File.WriteLine "$sysLang = (Get-Culture).TwoLetterISOLanguageName"
    File.WriteLine "$lang = if ($sysLang -eq 'de') { 'de' } elseif ($sysLang -eq 'nl') { 'nl' } else { 'en' }"
    File.WriteLine ""
    File.WriteLine "# Translations"
    File.WriteLine "$T = @{"
    File.WriteLine "  de = @{"
    File.WriteLine "    noInternet = 'Keine Internetverbindung!'"
    File.WriteLine "    termsDeclined = 'Nutzungsbedingungen nicht akzeptiert.'"
    File.WriteLine "    updateAvailable = 'Update verfuegbar!'"
    File.WriteLine "    updateNow = 'Jetzt aktualisieren?'"
    File.WriteLine "    newVersion = 'Neu'"
    File.WriteLine "    currentVersion = 'Aktuell'"
    File.WriteLine "    createShortcut = 'Desktop-Verknuepfung erstellen?'"
    File.WriteLine "    installNode = 'Node.js wird benoetigt. Installieren?'"
    File.WriteLine "    installNodeManual = 'Bitte manuell installieren: https://nodejs.org/'"
    File.WriteLine "    restartRequired = 'Bitte PC neu starten und erneut ausfuehren.'"
    File.WriteLine "    downloadFailed = 'Download fehlgeschlagen!'"
    File.WriteLine "    downloadingNode = 'Node.js wird heruntergeladen...'"
    File.WriteLine "    installingNode = 'Node.js wird installiert...'"
    File.WriteLine "    firstInstall = 'Erstinstallation...'"
    File.WriteLine "    downloading = 'Lade'"
    File.WriteLine "    installingModules = 'Module werden installiert (1-2 Min)...'"
    File.WriteLine "    updateModules = 'Module aktualisieren?'"
    File.WriteLine "    deletingModules = 'Module loeschen...'"
    File.WriteLine "    disclaimer100AI = '100% KI-generiert, ungeprueft. Fortfahren?'"
    File.WriteLine "  }"
    File.WriteLine "  en = @{"
    File.WriteLine "    noInternet = 'No internet connection!'"
    File.WriteLine "    termsDeclined = 'Terms not accepted.'"
    File.WriteLine "    updateAvailable = 'Update available!'"
    File.WriteLine "    updateNow = 'Update now?'"
    File.WriteLine "    newVersion = 'New'"
    File.WriteLine "    currentVersion = 'Current'"
    File.WriteLine "    createShortcut = 'Create desktop shortcut?'"
    File.WriteLine "    installNode = 'Node.js is required. Install?'"
    File.WriteLine "    installNodeManual = 'Please install manually: https://nodejs.org/'"
    File.WriteLine "    restartRequired = 'Please restart PC and run again.'"
    File.WriteLine "    downloadFailed = 'Download failed!'"
    File.WriteLine "    downloadingNode = 'Downloading Node.js...'"
    File.WriteLine "    installingNode = 'Installing Node.js...'"
    File.WriteLine "    firstInstall = 'First installation...'"
    File.WriteLine "    downloading = 'Downloading'"
    File.WriteLine "    installingModules = 'Installing modules (1-2 min)...'"
    File.WriteLine "    updateModules = 'Update modules?'"
    File.WriteLine "    deletingModules = 'Deleting modules...'"
    File.WriteLine "    disclaimer100AI = '100% AI-generated, unverified. Continue?'"
    File.WriteLine "  }"
    File.WriteLine "  nl = @{"
    File.WriteLine "    noInternet = 'Geen internetverbinding!'"
    File.WriteLine "    termsDeclined = 'Voorwaarden niet geaccepteerd.'"
    File.WriteLine "    updateAvailable = 'Update beschikbaar!'"
    File.WriteLine "    updateNow = 'Nu bijwerken?'"
    File.WriteLine "    newVersion = 'Nieuw'"
    File.WriteLine "    currentVersion = 'Huidig'"
    File.WriteLine "    createShortcut = 'Snelkoppeling op bureaublad maken?'"
    File.WriteLine "    installNode = 'Node.js is vereist. Installeren?'"
    File.WriteLine "    installNodeManual = 'Installeer handmatig: https://nodejs.org/'"
    File.WriteLine "    restartRequired = 'Start PC opnieuw en voer opnieuw uit.'"
    File.WriteLine "    downloadFailed = 'Download mislukt!'"
    File.WriteLine "    downloadingNode = 'Node.js downloaden...'"
    File.WriteLine "    installingNode = 'Node.js installeren...'"
    File.WriteLine "    firstInstall = 'Eerste installatie...'"
    File.WriteLine "    downloading = 'Downloaden'"
    File.WriteLine "    installingModules = 'Modules installeren (1-2 min)...'"
    File.WriteLine "    updateModules = 'Modules bijwerken?'"
    File.WriteLine "    deletingModules = 'Modules verwijderen...'"
    File.WriteLine "    disclaimer100AI = '100% AI-gegenereerd, niet geverifieerd. Doorgaan?'"
    File.WriteLine "  }"
    File.WriteLine "}"
    File.WriteLine "$t = $T[$lang]"
    File.WriteLine ""
    File.WriteLine "# Configuration"
    File.WriteLine "$GitHubApi = 'https://api.github.com/repos/3Dcut/multiLLM/commits/main'"
    File.WriteLine "$GitHubRaw = 'https://raw.githubusercontent.com/3Dcut/multiLLM/main'"
    File.WriteLine "$SoftwareDir = Join-Path $AppPath 'software'"
    File.WriteLine "$DataDir = Join-Path $SoftwareDir 'data'"
    File.WriteLine "if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir -Force | Out-Null }"
    File.WriteLine "$UpdateInfo = Join-Path $DataDir 'update-info.txt'"
    File.WriteLine "$DisclaimerAccepted = Join-Path $DataDir 'disclaimer-accepted.txt'"
    File.WriteLine ""
    File.WriteLine "# Functions"
    File.WriteLine "function Get-RemoteCommit {"
    File.WriteLine "    try {"
    File.WriteLine "        $response = Invoke-RestMethod -Uri $GitHubApi -Headers @{'User-Agent'='LLM-MultiChat'}"
    File.WriteLine "        return @{ sha = $response.sha; date = $response.commit.committer.date }"
    File.WriteLine "    } catch { return $null }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Get-LocalTimestamp {"
    File.WriteLine "    if (Test-Path $UpdateInfo) {"
    File.WriteLine "        $content = Get-Content $UpdateInfo"
    File.WriteLine "        foreach ($line in $content) {"
    File.WriteLine "            if ($line -match '^TIMESTAMP:(.+)$') { return $matches[1].Trim() }"
    File.WriteLine "        }"
    File.WriteLine "    }"
    File.WriteLine "    return ''"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Save-UpdateInfo($timestamp, $sha) {"
    File.WriteLine "    Set-Content -Path $UpdateInfo -Value @(""TIMESTAMP:$timestamp"", ""COMMIT:$sha"")"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Download-File($url, $dest) {"
    File.WriteLine "    $maxRetries = 3"
    File.WriteLine "    $retryDelay = 1000"
    File.WriteLine "    for ($i = 1; $i -le $maxRetries; $i++) {"
    File.WriteLine "        try {"
    File.WriteLine "            $destDir = Split-Path $dest -Parent"
    File.WriteLine "            if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }"
    File.WriteLine "            Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing -ErrorAction Stop -TimeoutSec 30"
    File.WriteLine "            if (Test-Path $dest) { return $true }"
    File.WriteLine "        } catch {"
    File.WriteLine "            if ($i -eq $maxRetries) {"
    File.WriteLine "                Write-Host ""Download failed after $maxRetries attempts: $url -> $dest - $($_.Exception.Message)"" -ForegroundColor Red"
    File.WriteLine "                return $false"
    File.WriteLine "            }"
    File.WriteLine "            Start-Sleep -Milliseconds $retryDelay"
    File.WriteLine "        }"
    File.WriteLine "    }"
    File.WriteLine "    return $false"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Show-Status($msg) {"
    File.WriteLine "    $statusFile = Join-Path $env:TEMP 'llm-multichat-status.txt'"
    File.WriteLine "    Set-Content -Path $statusFile -Value @('VERSION:LLM MultiChat', ""STATUS:$msg"")"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Close-Status {"
    File.WriteLine "    $statusFile = Join-Path $env:TEMP 'llm-multichat-status.txt'"
    File.WriteLine "    Set-Content -Path $statusFile -Value 'CLOSE'"
    File.WriteLine "    Start-Sleep -Milliseconds 500"
    File.WriteLine "    Remove-Item $statusFile -Force -ErrorAction SilentlyContinue"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Start-StatusWindow {"
    File.WriteLine "    $hta = Join-Path $SoftwareDir 'assets\status.hta'"
    File.WriteLine "    if (Test-Path $hta) { Start-Process mshta $hta }"
    File.WriteLine "    Start-Sleep -Milliseconds 500"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Show-Disclaimer {"
    File.WriteLine "    $hta = Join-Path $SoftwareDir 'assets\disclaimer.hta'"
    File.WriteLine "    $resultFile = Join-Path $env:TEMP 'llm-multichat-disclaimer.txt'"
    File.WriteLine "    Remove-Item $resultFile -Force -ErrorAction SilentlyContinue"
    File.WriteLine "    "
    File.WriteLine "    if (-not (Test-Path $hta)) {"
    File.WriteLine "        $r = [System.Windows.Forms.MessageBox]::Show($t.disclaimer100AI, 'LLM MultiChat', 'YesNo', 'Warning')"
    File.WriteLine "        return ($r -eq 'Yes')"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    Start-Process mshta $hta -Wait"
    File.WriteLine "    Start-Sleep -Milliseconds 200"
    File.WriteLine "    "
    File.WriteLine "    if (Test-Path $resultFile) {"
    File.WriteLine "        $result = (Get-Content $resultFile).Trim()"
    File.WriteLine "        Remove-Item $resultFile -Force"
    File.WriteLine "        if ($result -eq 'ACCEPTED') {"
    File.WriteLine "            Set-Content -Path $DisclaimerAccepted -Value (Get-Date)"
    File.WriteLine "            return $true"
    File.WriteLine "        }"
    File.WriteLine "    }"
    File.WriteLine "    return $false"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Install-NodeJS {"
    File.WriteLine "    $msi = Join-Path $env:TEMP 'node_setup.msi'"
    File.WriteLine "    $url = 'https://nodejs.org/dist/v20.11.0/node-v20.11.0-x64.msi'"
    File.WriteLine "    "
    File.WriteLine "    Show-Status $t.downloadingNode"
    File.WriteLine "    if (-not (Download-File $url $msi)) {"
    File.WriteLine "        Close-Status"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show($t.downloadFailed, 'Error', 'OK', 'Error')"
    File.WriteLine "        return $false"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    Show-Status $t.installingNode"
    File.WriteLine "    Start-Process msiexec -ArgumentList '/i', $msi, '/passive' -Wait"
    File.WriteLine "    Remove-Item $msi -Force -ErrorAction SilentlyContinue"
    File.WriteLine "    "
    File.WriteLine "    $env:Path = ""$env:ProgramFiles\nodejs;"" + $env:Path"
    File.WriteLine "    return $true"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Create-DesktopShortcut {"
    File.WriteLine "    $desktop = [Environment]::GetFolderPath('Desktop')"
    File.WriteLine "    $shortcut = Join-Path $desktop 'LLM MultiChat.lnk'"
    File.WriteLine "    $ws = New-Object -ComObject WScript.Shell"
    File.WriteLine "    $sc = $ws.CreateShortcut($shortcut)"
    File.WriteLine "    $sc.TargetPath = Join-Path $AppPath 'Start.vbs'"
    File.WriteLine "    $sc.WorkingDirectory = $AppPath"
    File.WriteLine "    $sc.Description = 'LLM MultiChat'"
    File.WriteLine "    $sc.Save()"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# === MAIN ==="
    File.WriteLine ""
    File.WriteLine "Add-Type -AssemblyName System.Windows.Forms"
    File.WriteLine ""
    File.WriteLine "# Check connection"
    File.WriteLine "$remote = Get-RemoteCommit"
    File.WriteLine "if (-not $remote) {"
    File.WriteLine "    if (-not (Test-Path (Join-Path $SoftwareDir 'src\main\main.js'))) {"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show($t.noInternet, 'Error', 'OK', 'Error')"
    File.WriteLine "        exit 1"
    File.WriteLine "    }"
    File.WriteLine "    exit 0"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "$localTs = Get-LocalTimestamp"
    File.WriteLine "$isFirstInstall = -not (Test-Path (Join-Path $SoftwareDir 'src\main\main.js'))"
    File.WriteLine "$needsUpdate = $remote.date -gt $localTs"
    File.WriteLine ""
    File.WriteLine "# Ensure assets directory exists"
    File.WriteLine "$assetsDir = Join-Path $SoftwareDir 'assets'"
    File.WriteLine "if (-not (Test-Path $assetsDir)) { New-Item -ItemType Directory -Path $assetsDir -Force | Out-Null }"
    File.WriteLine ""
    File.WriteLine "# Download disclaimer if needed (missing or not accepted)"
    File.WriteLine "$disclaimerPath = Join-Path $SoftwareDir 'assets\disclaimer.hta'"
    File.WriteLine "$pdfPath = Join-Path $AppPath 'security-report.pdf'"
    File.WriteLine "$disclaimerMissing = -not (Test-Path $disclaimerPath)"
    File.WriteLine "if ($disclaimerMissing -or ($needsUpdate -and -not (Test-Path $DisclaimerAccepted))) {"
    File.WriteLine "    if ($disclaimerMissing) {"
    File.WriteLine "        Show-Status $t.downloading"
    File.WriteLine "    }"
    File.WriteLine "    if (-not (Download-File ""$GitHubRaw/software/assets/disclaimer.hta"" $disclaimerPath)) {"
    File.WriteLine "        if ($disclaimerMissing) {"
    File.WriteLine "            Close-Status"
    File.WriteLine "            [System.Windows.Forms.MessageBox]::Show('Disclaimer konnte nicht heruntergeladen werden.', 'Error', 'OK', 'Error')"
    File.WriteLine "            exit 1"
    File.WriteLine "        }"
    File.WriteLine "    }"
    File.WriteLine "    if ($disclaimerMissing -and -not (Test-Path $pdfPath)) {"
    File.WriteLine "        Download-File ""$GitHubRaw/security-report.pdf"" $pdfPath"
    File.WriteLine "    }"
    File.WriteLine "    if ($disclaimerMissing) {"
    File.WriteLine "        Start-Sleep -Milliseconds 500"
    File.WriteLine "    }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# Check disclaimer"
    File.WriteLine "if (-not (Test-Path $DisclaimerAccepted)) {"
    File.WriteLine "    if (-not (Show-Disclaimer)) {"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show($t.termsDeclined, 'LLM MultiChat', 'OK', 'Information')"
    File.WriteLine "        exit 0"
    File.WriteLine "    }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# Files to download (note: structure changed - files are now in subdirectories)"
    File.WriteLine "$files = @('README.md','security-report.pdf')"
    File.WriteLine "$appFiles = @{'software/app/package.json'='package.json'}"
    File.WriteLine "$srcFiles = @{'software/src/main/main.js'='main.js';'software/src/preload/preload.js'='preload.js'; `"
    File.WriteLine "             'software/src/renderer/renderer.js'='renderer.js'; `"
    File.WriteLine "             'software/src/renderer/conversation-controller.js'='conversation-controller.js'; `"
    File.WriteLine "             'software/src/renderer/utils/i18n.js'='i18n.js'; `"
    File.WriteLine "             'software/src/renderer/utils/vote-patterns.js'='vote-patterns.js'; `"
    File.WriteLine "             'software/src/renderer/utils/response-monitor.js'='response-monitor.js'; `"
    File.WriteLine "             'software/src/ui/index.html'='index.html';'software/src/ui/styles.css'='styles.css'}"
    File.WriteLine "$assetsFiles = @{'software/assets/status.hta'='status.hta';'software/assets/disclaimer.hta'='disclaimer.hta'; `"
    File.WriteLine "                'software/assets/Uninstall.hta'='Uninstall.hta'}"
    File.WriteLine "$configFiles = @{'software/config/config.json.template'='config.json.template'; `"
    File.WriteLine "                'software/config/user-settings.json.template'='user-settings.json.template'}"
    File.WriteLine ""
    File.WriteLine "# First install"
    File.WriteLine "if ($isFirstInstall) {"
    File.WriteLine "    Download-File ""$GitHubRaw/software/assets/status.hta"" (Join-Path $SoftwareDir 'assets\status.hta')"
    File.WriteLine "    Start-StatusWindow"
    File.WriteLine "    Show-Status $t.firstInstall"
    File.WriteLine "    "
    File.WriteLine "    foreach ($f in $files) {"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$f"" (Join-Path $AppPath $f)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Create directory structure"
    File.WriteLine "    $dirs = @('software\src\main','software\src\preload','software\src\renderer\utils','software\src\ui','software\config','software\assets','software\app')"
    File.WriteLine "    foreach ($d in $dirs) {"
    File.WriteLine "        $dirPath = Join-Path $AppPath $d"
    File.WriteLine "        if (-not (Test-Path $dirPath)) { New-Item -ItemType Directory -Path $dirPath -Force | Out-Null }"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download app files (package.json)"
    File.WriteLine "    foreach ($entry in $appFiles.GetEnumerator()) {"
    File.WriteLine "        Show-Status ""$($t.downloading) $($entry.Value)..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$($entry.Key)"" (Join-Path $SoftwareDir ""app\$($entry.Value)"")"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download source files"
    File.WriteLine "    foreach ($key in $srcFiles.Keys) {"
    File.WriteLine "        $f = $srcFiles[$key]"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$key"" (Join-Path $AppPath $key)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download asset files"
    File.WriteLine "    foreach ($key in $assetsFiles.Keys) {"
    File.WriteLine "        $f = $assetsFiles[$key]"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$key"" (Join-Path $AppPath $key)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download config templates"
    File.WriteLine "    foreach ($key in $configFiles.Keys) {"
    File.WriteLine "        $f = $configFiles[$key]"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$key"" (Join-Path $AppPath $key)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Initialize configs"
    File.WriteLine "    $cfgTemplate = Join-Path $SoftwareDir 'config\config.json.template'"
    File.WriteLine "    $cfg = Join-Path $SoftwareDir 'config\config.json'"
    File.WriteLine "    if ((Test-Path $cfgTemplate) -and -not (Test-Path $cfg)) { Copy-Item $cfgTemplate $cfg }"
    File.WriteLine "    "
    File.WriteLine "    $usTemplate = Join-Path $SoftwareDir 'config\user-settings.json.template'"
    File.WriteLine "    $us = Join-Path $SoftwareDir 'config\user-settings.json'"
    File.WriteLine "    if ((Test-Path $usTemplate) -and -not (Test-Path $us)) {"
    File.WriteLine "        $settings = Get-Content $usTemplate | ConvertFrom-Json"
    File.WriteLine "        $settings.language = $lang"
    File.WriteLine "        $settings | ConvertTo-Json | Set-Content $us"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    Save-UpdateInfo $remote.date $remote.sha"
    File.WriteLine "}"
    File.WriteLine "# Update"
    File.WriteLine "elseif ($needsUpdate) {"
    File.WriteLine "    Download-File ""$GitHubRaw/software/assets/status.hta"" (Join-Path $SoftwareDir 'assets\status.hta')"
    File.WriteLine "    Start-StatusWindow"
    File.WriteLine "    Show-Status 'Update wird ausgefuehrt...'"
    File.WriteLine "    "
    File.WriteLine "    foreach ($f in $files) {"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$f"" (Join-Path $AppPath $f)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download app files (package.json)"
    File.WriteLine "    foreach ($entry in $appFiles.GetEnumerator()) {"
    File.WriteLine "        Show-Status ""$($t.downloading) $($entry.Value)..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$($entry.Key)"" (Join-Path $SoftwareDir ""app\$($entry.Value)"")"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download source files"
    File.WriteLine "    foreach ($key in $srcFiles.Keys) {"
    File.WriteLine "        $f = $srcFiles[$key]"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$key"" (Join-Path $AppPath $key)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download asset files"
    File.WriteLine "    foreach ($key in $assetsFiles.Keys) {"
    File.WriteLine "        $f = $assetsFiles[$key]"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$key"" (Join-Path $AppPath $key)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Download config templates"
    File.WriteLine "    foreach ($key in $configFiles.Keys) {"
    File.WriteLine "        $f = $configFiles[$key]"
    File.WriteLine "        Show-Status ""$($t.downloading) $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$key"" (Join-Path $AppPath $key)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    Save-UpdateInfo $remote.date $remote.sha"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# Check Node.js"
    File.WriteLine "$nodeExists = $null -ne (Get-Command node -ErrorAction SilentlyContinue)"
    File.WriteLine "if (-not $nodeExists) {"
    File.WriteLine "    Close-Status"
    File.WriteLine "    $r = [System.Windows.Forms.MessageBox]::Show($t.installNode, 'LLM MultiChat', 'YesNo', 'Question')"
    File.WriteLine "    if ($r -eq 'No') {"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show($t.installNodeManual, 'Info', 'OK', 'Information')"
    File.WriteLine "        exit 0"
    File.WriteLine "    }"
    File.WriteLine "    Download-File ""$GitHubRaw/software/assets/status.hta"" (Join-Path $SoftwareDir 'assets\status.hta')"
    File.WriteLine "    Start-StatusWindow"
    File.WriteLine "    if (-not (Install-NodeJS)) { exit 1 }"
    File.WriteLine "    "
    File.WriteLine "    $nodeExists = $null -ne (Get-Command node -ErrorAction SilentlyContinue)"
    File.WriteLine "    if (-not $nodeExists) {"
    File.WriteLine "        Close-Status"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show($t.restartRequired, 'Info', 'OK', 'Information')"
    File.WriteLine "        exit 0"
    File.WriteLine "    }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# npm install"
    File.WriteLine "$electron = Join-Path $SoftwareDir 'app\node_modules\.bin\electron.cmd'"
    File.WriteLine "if (-not (Test-Path $electron)) {"
    File.WriteLine "    $htaExists = Test-Path (Join-Path $SoftwareDir 'assets\status.hta')"
    File.WriteLine "    if (-not $htaExists) {"
    File.WriteLine "        Download-File ""$GitHubRaw/software/assets/status.hta"" (Join-Path $SoftwareDir 'assets\status.hta')"
    File.WriteLine "    }"
    File.WriteLine "    Start-StatusWindow"
    File.WriteLine "    Show-Status $t.installingModules"
    File.WriteLine "    Push-Location (Join-Path $SoftwareDir 'app')"
    File.WriteLine "    & npm install 2>&1 | Out-Null"
    File.WriteLine "    Pop-Location"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# Offer desktop shortcut (only on first install or if it doesn't exist)"
    File.WriteLine "$desktop = [Environment]::GetFolderPath('Desktop')"
    File.WriteLine "$shortcut = Join-Path $desktop 'LLM MultiChat.lnk'"
    File.WriteLine "if ($isFirstInstall -or -not (Test-Path $shortcut)) {"
    File.WriteLine "    Close-Status"
    File.WriteLine "    $r = [System.Windows.Forms.MessageBox]::Show($t.createShortcut, 'LLM MultiChat', 'YesNo', 'Question')"
    File.WriteLine "    if ($r -eq 'Yes') { Create-DesktopShortcut }"
    File.WriteLine "} else {"
    File.WriteLine "    Close-Status"
    File.WriteLine "}"
    
    File.Close
End Sub
