' LLM MultiChat - Starter
' Erstellt temporaeres PowerShell-Script fuer Updates

Option Explicit

Dim WshShell, FSO, AppPath, TempPath, PsScript, Result
Set WshShell = CreateObject("WScript.Shell")
Set FSO = CreateObject("Scripting.FileSystemObject")

AppPath = FSO.GetParentFolderName(WScript.ScriptFullName)
TempPath = WshShell.ExpandEnvironmentStrings("%TEMP%")
PsScript = TempPath & "\llm-multichat-setup.ps1"

' PowerShell-Script erstellen
CreateSetupScript

' PowerShell ausfuehren
Result = WshShell.Run("powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & PsScript & """ -AppPath """ & AppPath & """", 0, True)

' Temporaeres Script loeschen
On Error Resume Next
FSO.DeleteFile PsScript
On Error GoTo 0

' Wenn Setup erfolgreich, App starten
If FSO.FileExists(AppPath & "\main.js") Then
    WshShell.CurrentDirectory = AppPath
    WshShell.Run "cmd /c npm start", 0, False
End If

' ============================================

Sub CreateSetupScript()
    Dim File
    Set File = FSO.CreateTextFile(PsScript, True)
    
    File.WriteLine "param([string]$AppPath)"
    File.WriteLine ""
    File.WriteLine "$ErrorActionPreference = 'SilentlyContinue'"
    File.WriteLine "$ProgressPreference = 'SilentlyContinue'"
    File.WriteLine ""
    File.WriteLine "# Konfiguration"
    File.WriteLine "$GitHubApi = 'https://api.github.com/repos/3Dcut/multiLLM/commits/main'"
    File.WriteLine "$GitHubRaw = 'https://raw.githubusercontent.com/3Dcut/multiLLM/main'"
    File.WriteLine "$UpdateInfo = Join-Path $AppPath 'update-info.txt'"
    File.WriteLine "$DisclaimerAccepted = Join-Path $AppPath 'disclaimer-accepted.txt'"
    File.WriteLine ""
    File.WriteLine "# Funktionen"
    File.WriteLine "function Get-RemoteCommit {"
    File.WriteLine "    try {"
    File.WriteLine "        $response = Invoke-RestMethod -Uri $GitHubApi -Headers @{'User-Agent'='LLM-MultiChat'}"
    File.WriteLine "        return @{ sha = $response.sha; date = $response.commit.committer.date }"
    File.WriteLine "    } catch { return $null }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Get-LocalTimestamp {"
    File.WriteLine "    if (Test-Path $UpdateInfo) {"
    File.WriteLine "        $content = Get-Content $UpdateInfo"
    File.WriteLine "        foreach ($line in $content) {"
    File.WriteLine "            if ($line -match '^TIMESTAMP:(.+)$') { return $matches[1].Trim() }"
    File.WriteLine "        }"
    File.WriteLine "    }"
    File.WriteLine "    return ''"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Save-UpdateInfo($timestamp, $sha) {"
    File.WriteLine "    Set-Content -Path $UpdateInfo -Value @(""TIMESTAMP:$timestamp"", ""COMMIT:$sha"")"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Download-File($url, $dest) {"
    File.WriteLine "    try {"
    File.WriteLine "        Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing"
    File.WriteLine "        return $true"
    File.WriteLine "    } catch { return $false }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Show-Status($msg) {"
    File.WriteLine "    $statusFile = Join-Path $env:TEMP 'llm-multichat-status.txt'"
    File.WriteLine "    Set-Content -Path $statusFile -Value @('VERSION:LLM MultiChat', ""STATUS:$msg"")"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Close-Status {"
    File.WriteLine "    $statusFile = Join-Path $env:TEMP 'llm-multichat-status.txt'"
    File.WriteLine "    Set-Content -Path $statusFile -Value 'CLOSE'"
    File.WriteLine "    Start-Sleep -Milliseconds 500"
    File.WriteLine "    Remove-Item $statusFile -Force -ErrorAction SilentlyContinue"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Start-StatusWindow {"
    File.WriteLine "    $hta = Join-Path $AppPath 'status.hta'"
    File.WriteLine "    if (Test-Path $hta) { Start-Process mshta $hta }"
    File.WriteLine "    Start-Sleep -Milliseconds 500"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Show-Disclaimer {"
    File.WriteLine "    $hta = Join-Path $AppPath 'disclaimer.hta'"
    File.WriteLine "    $resultFile = Join-Path $env:TEMP 'llm-multichat-disclaimer.txt'"
    File.WriteLine "    Remove-Item $resultFile -Force -ErrorAction SilentlyContinue"
    File.WriteLine "    "
    File.WriteLine "    if (-not (Test-Path $hta)) {"
    File.WriteLine "        $r = [System.Windows.Forms.MessageBox]::Show('100% KI-generiert, ungeprueft. Fortfahren?', 'LLM MultiChat', 'YesNo', 'Warning')"
    File.WriteLine "        return ($r -eq 'Yes')"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    Start-Process mshta $hta -Wait"
    File.WriteLine "    Start-Sleep -Milliseconds 200"
    File.WriteLine "    "
    File.WriteLine "    if (Test-Path $resultFile) {"
    File.WriteLine "        $result = (Get-Content $resultFile).Trim()"
    File.WriteLine "        Remove-Item $resultFile -Force"
    File.WriteLine "        if ($result -eq 'ACCEPTED') {"
    File.WriteLine "            Set-Content -Path $DisclaimerAccepted -Value (Get-Date)"
    File.WriteLine "            return $true"
    File.WriteLine "        }"
    File.WriteLine "    }"
    File.WriteLine "    return $false"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Install-NodeJS {"
    File.WriteLine "    $msi = Join-Path $env:TEMP 'node_setup.msi'"
    File.WriteLine "    $url = 'https://nodejs.org/dist/v20.11.0/node-v20.11.0-x64.msi'"
    File.WriteLine "    "
    File.WriteLine "    Show-Status 'Node.js wird heruntergeladen...'"
    File.WriteLine "    if (-not (Download-File $url $msi)) {"
    File.WriteLine "        Close-Status"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show('Download fehlgeschlagen!', 'Fehler', 'OK', 'Error')"
    File.WriteLine "        return $false"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    Show-Status 'Node.js wird installiert...'"
    File.WriteLine "    Start-Process msiexec -ArgumentList '/i', $msi, '/passive' -Wait"
    File.WriteLine "    Remove-Item $msi -Force -ErrorAction SilentlyContinue"
    File.WriteLine "    "
    File.WriteLine "    $env:Path = ""$env:ProgramFiles\nodejs;"" + $env:Path"
    File.WriteLine "    return $true"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "function Create-DesktopShortcut {"
    File.WriteLine "    $desktop = [Environment]::GetFolderPath('Desktop')"
    File.WriteLine "    $shortcut = Join-Path $desktop 'LLM MultiChat.lnk'"
    File.WriteLine "    $ws = New-Object -ComObject WScript.Shell"
    File.WriteLine "    $sc = $ws.CreateShortcut($shortcut)"
    File.WriteLine "    $sc.TargetPath = Join-Path $AppPath 'Start.vbs'"
    File.WriteLine "    $sc.WorkingDirectory = $AppPath"
    File.WriteLine "    $sc.Description = 'LLM MultiChat starten'"
    File.WriteLine "    $sc.Save()"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# === HAUPTPROGRAMM ==="
    File.WriteLine ""
    File.WriteLine "Add-Type -AssemblyName System.Windows.Forms"
    File.WriteLine ""
    File.WriteLine "# Verbindung pruefen"
    File.WriteLine "$remote = Get-RemoteCommit"
    File.WriteLine "if (-not $remote) {"
    File.WriteLine "    if (-not (Test-Path (Join-Path $AppPath 'main.js'))) {"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show('Keine Internetverbindung!', 'Fehler', 'OK', 'Error')"
    File.WriteLine "        exit 1"
    File.WriteLine "    }"
    File.WriteLine "    exit 0"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "$localTs = Get-LocalTimestamp"
    File.WriteLine "$isFirstInstall = -not (Test-Path (Join-Path $AppPath 'main.js'))"
    File.WriteLine "$needsUpdate = $remote.date -gt $localTs"
    File.WriteLine ""
    File.WriteLine "# Disclaimer laden"
    File.WriteLine "if ($isFirstInstall -or ($needsUpdate -and -not (Test-Path $DisclaimerAccepted))) {"
    File.WriteLine "    Download-File ""$GitHubRaw/disclaimer.hta"" (Join-Path $AppPath 'disclaimer.hta')"
    File.WriteLine "    Download-File ""$GitHubRaw/security-report.pdf"" (Join-Path $AppPath 'security-report.pdf')"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# Disclaimer pruefen"
    File.WriteLine "if (-not (Test-Path $DisclaimerAccepted)) {"
    File.WriteLine "    if (-not (Show-Disclaimer)) {"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show('Nutzungsbedingungen nicht akzeptiert.', 'LLM MultiChat', 'OK', 'Information')"
    File.WriteLine "        exit 0"
    File.WriteLine "    }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# Dateien"
    File.WriteLine "$files = @('main.js','renderer.js','preload.js','index.html','styles.css','vote-patterns.js',"
    File.WriteLine "           'package.json','README.md','status.hta','disclaimer.hta','Uninstall.hta',"
    File.WriteLine "           'config.json.template','user-settings.json.template','security-report.pdf')"
    File.WriteLine ""
    File.WriteLine "# Erstinstallation"
    File.WriteLine "if ($isFirstInstall) {"
    File.WriteLine "    Download-File ""$GitHubRaw/status.hta"" (Join-Path $AppPath 'status.hta')"
    File.WriteLine "    Start-StatusWindow"
    File.WriteLine "    Show-Status 'Erstinstallation...'"
    File.WriteLine "    "
    File.WriteLine "    foreach ($f in $files) {"
    File.WriteLine "        Show-Status ""Lade $f..."""
    File.WriteLine "        Download-File ""$GitHubRaw/$f"" (Join-Path $AppPath $f)"
    File.WriteLine "    }"
    File.WriteLine "    "
    File.WriteLine "    # Configs initialisieren"
    File.WriteLine "    $cfgTemplate = Join-Path $AppPath 'config.json.template'"
    File.WriteLine "    $cfg = Join-Path $AppPath 'config.json'"
    File.WriteLine "    if ((Test-Path $cfgTemplate) -and -not (Test-Path $cfg)) { Copy-Item $cfgTemplate $cfg }"
    File.WriteLine "    "
    File.WriteLine "    $usTemplate = Join-Path $AppPath 'user-settings.json.template'"
    File.WriteLine "    $us = Join-Path $AppPath 'user-settings.json'"
    File.WriteLine "    if ((Test-Path $usTemplate) -and -not (Test-Path $us)) { Copy-Item $usTemplate $us }"
    File.WriteLine "    "
    File.WriteLine "    Save-UpdateInfo $remote.date $remote.sha"
    File.WriteLine "    "
    File.WriteLine "    # Desktop-Verknuepfung anbieten"
    File.WriteLine "    Close-Status"
    File.WriteLine "    $r = [System.Windows.Forms.MessageBox]::Show('Desktop-Verknuepfung erstellen?', 'LLM MultiChat', 'YesNo', 'Question')"
    File.WriteLine "    if ($r -eq 'Yes') { Create-DesktopShortcut }"
    File.WriteLine "}"
    File.WriteLine "# Update"
    File.WriteLine "elseif ($needsUpdate) {"
    File.WriteLine "    $r = [System.Windows.Forms.MessageBox]::Show(""Update verfuegbar!`n`nNeu: $($remote.date)`nAktuell: $localTs`n`nJetzt aktualisieren?"", 'LLM MultiChat', 'YesNo', 'Question')"
    File.WriteLine "    if ($r -eq 'Yes') {"
    File.WriteLine "        Download-File ""$GitHubRaw/status.hta"" (Join-Path $AppPath 'status.hta')"
    File.WriteLine "        Start-StatusWindow"
    File.WriteLine "        foreach ($f in $files) {"
    File.WriteLine "            Show-Status ""Lade $f..."""
    File.WriteLine "            Download-File ""$GitHubRaw/$f"" (Join-Path $AppPath $f)"
    File.WriteLine "        }"
    File.WriteLine "        Save-UpdateInfo $remote.date $remote.sha"
    File.WriteLine "        "
    File.WriteLine "        $nm = Join-Path $AppPath 'node_modules'"
    File.WriteLine "        if (Test-Path $nm) {"
    File.WriteLine "            Close-Status"
    File.WriteLine "            $r = [System.Windows.Forms.MessageBox]::Show('Module aktualisieren?', 'LLM MultiChat', 'YesNo', 'Question')"
    File.WriteLine "            if ($r -eq 'Yes') {"
    File.WriteLine "                Start-StatusWindow"
    File.WriteLine "                Show-Status 'Module loeschen...'"
    File.WriteLine "                Remove-Item $nm -Recurse -Force"
    File.WriteLine "            }"
    File.WriteLine "        }"
    File.WriteLine "    }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# Node.js pruefen"
    File.WriteLine "$nodeExists = $null -ne (Get-Command node -ErrorAction SilentlyContinue)"
    File.WriteLine "if (-not $nodeExists) {"
    File.WriteLine "    Close-Status"
    File.WriteLine "    $r = [System.Windows.Forms.MessageBox]::Show('Node.js installieren?', 'LLM MultiChat', 'YesNo', 'Question')"
    File.WriteLine "    if ($r -eq 'No') {"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show('Bitte manuell: https://nodejs.org/', 'Info', 'OK', 'Information')"
    File.WriteLine "        exit 0"
    File.WriteLine "    }"
    File.WriteLine "    Download-File ""$GitHubRaw/status.hta"" (Join-Path $AppPath 'status.hta')"
    File.WriteLine "    Start-StatusWindow"
    File.WriteLine "    if (-not (Install-NodeJS)) { exit 1 }"
    File.WriteLine "    "
    File.WriteLine "    $nodeExists = $null -ne (Get-Command node -ErrorAction SilentlyContinue)"
    File.WriteLine "    if (-not $nodeExists) {"
    File.WriteLine "        Close-Status"
    File.WriteLine "        [System.Windows.Forms.MessageBox]::Show('Bitte PC neu starten.', 'Info', 'OK', 'Information')"
    File.WriteLine "        exit 0"
    File.WriteLine "    }"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "# npm install"
    File.WriteLine "$electron = Join-Path $AppPath 'node_modules\.bin\electron.cmd'"
    File.WriteLine "if (-not (Test-Path $electron)) {"
    File.WriteLine "    $htaExists = Test-Path (Join-Path $AppPath 'status.hta')"
    File.WriteLine "    if (-not $htaExists) {"
    File.WriteLine "        Download-File ""$GitHubRaw/status.hta"" (Join-Path $AppPath 'status.hta')"
    File.WriteLine "    }"
    File.WriteLine "    Start-StatusWindow"
    File.WriteLine "    Show-Status 'Module werden installiert (1-2 Min)...'"
    File.WriteLine "    Push-Location $AppPath"
    File.WriteLine "    & npm install 2>&1 | Out-Null"
    File.WriteLine "    Pop-Location"
    File.WriteLine "}"
    File.WriteLine ""
    File.WriteLine "Close-Status"
    
    File.Close
End Sub
